"""Synchronisation package with four standalone methods plus a selection pipeline."""

from .core import (
    AlignmentSeries,
    OffsetEstimate,
    SyncModel,
    add_vector_norms,
    apply_linear_time_transform,
    apply_sync_model,
    build_activity_signal,
    build_alignment_series,
    compute_sync_correlations,
    estimate_lag,
    estimate_offset,
    estimate_sync_model,
    fit_sync_from_paths,
    load_stream,
    load_sync_model,
    remove_dropouts,
    resample_aligned_stream,
    resample_stream,
    resample_to_reference_timestamps,
    save_sync_model,
)
from .pipeline import (
    ALL_METHODS,
    METHOD_LABELS,
    METHOD_STAGES,
    MethodQuality,
    MethodResult,
    RecordingResult,
    SyncSelectionResult,
    apply_selection,
    compare_sync_models,
    print_comparison,
    print_selection_result,
    prune_method_stage_directories,
    select_best_sync_method,
    synchronize_recording_all_methods,
    synchronize_session,
)
from .plotting import plot_method_scores, plot_methods_norm_grid, plot_synced_norm_overlay
from .sync_cal import CalibrationWindowResult, estimate_sync_from_calibration
from .sync_lida import estimate_sync_from_lida
from .sync_online import estimate_sync_from_opening_anchor, load_characterised_drift
from .sync_sda import estimate_sync_from_sda

__all__ = [
    "AlignmentSeries",
    "OffsetEstimate",
    "SyncModel",
    "add_vector_norms",
    "apply_linear_time_transform",
    "apply_sync_model",
    "build_activity_signal",
    "build_alignment_series",
    "compute_sync_correlations",
    "estimate_lag",
    "estimate_offset",
    "estimate_sync_model",
    "fit_sync_from_paths",
    "load_stream",
    "load_sync_model",
    "remove_dropouts",
    "resample_aligned_stream",
    "resample_stream",
    "resample_to_reference_timestamps",
    "save_sync_model",
    "estimate_sync_from_sda",
    "estimate_sync_from_lida",
    "CalibrationWindowResult",
    "estimate_sync_from_calibration",
    "estimate_sync_from_opening_anchor",
    "load_characterised_drift",
    "ALL_METHODS",
    "METHOD_LABELS",
    "METHOD_STAGES",
    "MethodQuality",
    "MethodResult",
    "RecordingResult",
    "SyncSelectionResult",
    "apply_selection",
    "compare_sync_models",
    "print_comparison",
    "print_selection_result",
    "prune_method_stage_directories",
    "select_best_sync_method",
    "synchronize_recording_all_methods",
    "synchronize_session",
    "plot_method_scores",
    "plot_methods_norm_grid",
    "plot_synced_norm_overlay",
]
